package UI;

import java.awt.Dimension;
import java.awt.Toolkit;

public class quayso_ui extends javax.swing.JFrame {
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    public String[] data_from_server;

    public quayso_ui() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        input_call_number = new javax.swing.JTextField();
        btn_call = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quay số");

        btn_call.setText("Gọi");
        btn_call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_callActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(input_call_number, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btn_call)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(input_call_number, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btn_call)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_callActionPerformed
        this.call(input_call_number.getText());
    }//GEN-LAST:event_btn_callActionPerformed
    
    public void call(String key){
        this.initcall("request_call"); // khởi tạo với chế độ yêu cầu
    }
    
    public void initcall(String mode){//request_call
//        ChatClient.calling = true;
//        
//        call_ui call = new call_ui();
//        call.setTitle(input_call_number.getText());
//        //call.fr_ID = fr_ID;
//        //call.fr_chat = this;
//        call.init_audio();
//        call.init_player();
//        
//        int x,y;
//        x = this.getLocation().x+this.getWidth();
//        y = this.getLocation().y;
//        if(x+call.getWidth()>dim.width)
//        x = this.getLocation().x-call.getWidth();
//        call.setLocation(x, y);
//        call.setVisible(true);
//                
//        DataSocket dtsk = new DataSocket();
//        dtsk.setAction(mode);
//        dtsk.setAccept(true);
//        String data[] = new String[4];
//        data[0] = String.valueOf(ChatClient.curentAccount.getPhoneNumber());
//        //data[1] = String.valueOf(fr_ID);
//        data[2] = call.my_ip;
//        data[3] = String.valueOf(call.my_port);
//        dtsk.setData(data);
//        ObjectOutputStream dout;
//            try {
//                dout = new ObjectOutputStream(ChatClient.socket.getOutputStream());
//                dout.writeObject(dtsk);
//                System.out.println("cuộc gọi được thiết lập: đồng ý");
//            } catch (IOException ex) {
//                Logger.getLogger(account_call_ui.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        if(mode.equalsIgnoreCase("respon_call")){
//            try {
//            // nếu chấp chận thì khởi tạo phần thu âm
//                call.init_recorder(InetAddress.getByName(this.data_from_server[2]), Integer.valueOf(this.data_from_server[3]));
//                call.lb_status.setText("Đã kết nối");
//            } catch (UnknownHostException ex) {
//                Logger.getLogger(account_call_ui.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quayso_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new quayso_ui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_call;
    public javax.swing.JTextField input_call_number;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
